// The getting-started tutorial, performed end to end against a real model.
//
// The guide in tutorial/ is GENERATED by this script rather than written by
// hand, so the documentation cannot drift from the app: every screenshot is
// the real UI, every agent reply is a real model turn, and if a step stops
// working the guide fails to build.
//
// Each chapter carries numbered, user-facing instructions — what to click and
// what to type — so a reader can follow along in their own install.
//
// Env: BASE, OUT, LOG, MODEL, ENDPOINT (see scripts/tutorial.sh)

import { chromium } from 'playwright-core';
import { writeFileSync, readFileSync, mkdirSync } from 'node:fs';

const BASE = process.env.BASE || 'http://127.0.0.1:18120';
const OUT = process.env.OUT || '/tmp/qm-tutorial';
const LOG = process.env.LOG || '';
const MODEL = process.env.MODEL || 'unknown';
const ENDPOINT = process.env.ENDPOINT || 'unknown';
mkdirSync(OUT, { recursive: true });

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const log = (...a) => console.log('[tutorial]', ...a);
const TURN_TIMEOUT = 240_000;

const chapters = [];
let chapter = null;
let seq = 0;
let failures = 0;

const browser = await chromium.launch({ channel: 'chrome', headless: true });

/// Each person gets their own browser context, so their session cookies are
/// genuinely separate — this is three people, not one person switching hats.
async function person(name) {
  const ctx = await browser.newContext({ viewport: { width: 1320, height: 980 } });
  ctx.on('page', (p) => p.on('dialog', (d) => d.accept().catch(() => {})));
  return { name, ctx, page: await ctx.newPage() };
}

/// A numbered instruction the reader follows.
function step(text) {
  chapter.steps.push({ kind: 'step', text });
  log('   ▸', text.replace(/\*\*/g, '').slice(0, 90));
}

/// Explanatory prose between instructions.
function note(text) {
  chapter.steps.push({ kind: 'note', text });
}

/// A screenshot of what the reader should be seeing now.
///
/// A `position: sticky` header is re-painted partway down a full-page capture,
/// which looks like a rendering bug in the finished guide. It is pinned to the
/// top for the duration of the shot and restored afterwards.
async function shot(page, caption, opts = {}) {
  seq += 1;
  const file = String(seq).padStart(2, '0') + '.png';
  const unstick = opts.full
    ? await page.addStyleTag({ content: '.topbar { position: static !important; }' }).catch(() => null)
    : null;
  await page.screenshot({ path: `${OUT}/${file}`, fullPage: !!opts.full });
  if (unstick) await unstick.evaluate((el) => el.remove()).catch(() => {});
  chapter.steps.push({ kind: 'shot', file, caption });
  log('   📸', caption.slice(0, 80));
}

function check(condition, what) {
  if (!condition) throw new Error(what);
}

async function chapterRun(title, intro, fn) {
  chapter = { title, intro, steps: [], status: 'pass', error: '' };
  chapters.push(chapter);
  log('▶', title);
  try {
    await fn();
  } catch (e) {
    chapter.status = 'fail';
    chapter.error = String((e && e.message) || e);
    failures += 1;
    log('   ✗ FAIL:', chapter.error);
  }
}

async function signIn(who, email) {
  await who.page.goto(`${BASE}/auth/login`, { waitUntil: 'load' });
  await who.page.fill('#email', email);
  const before = readFileSync(LOG, 'utf8').length;
  await Promise.all([
    who.page.waitForNavigation({ timeout: 30_000 }),
    who.page.click('form[action="/auth/request"] button[type=submit]', { noWaitAfter: true }),
  ]);
  let link = '';
  for (let i = 0; i < 80 && !link; i++) {
    const tail = readFileSync(LOG, 'utf8').slice(before);
    const found = tail.match(/http:\/\/[^\s"]*\/auth\/callback\?token=[A-Za-z0-9%&=.-]+/g);
    if (found) link = found[found.length - 1];
    else await sleep(250);
  }
  check(link, `no sign-in link appeared for ${email}`);
  await who.page.goto(link, { waitUntil: 'load' });
  check(!who.page.url().includes('/auth/login'), `${email} could not sign in`);
}

async function ask(who, text) {
  await who.page.fill('#composer textarea', text);
  await Promise.all([
    who.page.waitForNavigation({ timeout: TURN_TIMEOUT, waitUntil: 'load' }),
    who.page.click('#composer button[type=submit]', { noWaitAfter: true, timeout: 30_000 }),
  ]);
  await sleep(300);
}

async function lastReply(page) {
  const entries = page.locator('.entry.assistant .body');
  const count = await entries.count();
  return count ? (await entries.nth(count - 1).textContent()).trim() : '';
}

async function openSession(who, scope, title) {
  await who.page.goto(`${BASE}/sessions`, { waitUntil: 'load' });
  await who.page.selectOption('#scope', scope);
  if (title) await who.page.fill('#title', title);
  await Promise.all([
    who.page.waitForNavigation({ timeout: 30_000 }),
    who.page.click('form[action="/sessions"] button[type=submit]', { noWaitAfter: true }),
  ]);
  return who.page.url();
}

// ---------------------------------------------------------------------------

const admin = await person('admin');
const ada = await person('ada');
const dana = await person('dana');

await chapterRun(
  'Sign in as the administrator',
  'qm has no passwords. You sign in with a link sent to your email address, which works ' +
    'exactly once and expires after fifteen minutes. On a fresh install the administrator is ' +
    'whoever `[auth].admin_email` names in `config.toml` — start the server, then follow along.',
  async () => {
    step('Open **http://127.0.0.1:8080** in a browser. You will be redirected to the sign-in page, because every page in qm requires you to be signed in.');
    await admin.page.goto(`${BASE}/admin`, { waitUntil: 'load' });
    check(admin.page.url().includes('/auth/login'), 'the admin page should be locked');
    await shot(admin.page, 'Any page you ask for while signed out sends you here, remembering where you were headed so you land back there afterwards.');

    step('Type the address you set as `[auth].admin_email` and press **Email me a link**.');
    note(
      'You always get the same confirmation page, whether or not that address is allowed to ' +
        'sign in. That is deliberate: a different response for an unknown address would let ' +
        'anyone test whether a person works at your company.',
    );

    step('Find the link. With the default `email_mode = "console"` there is no mail provider, so the link is written to the server log instead — look for a line containing `sign-in link`. To send real email, set `email_mode = "resend"`, a verified `from_address`, and the `QM_EMAIL_API_KEY` environment variable.');
    await signIn(admin, 'admin@acme.test');

    step('Open the link. You are signed in, and the **Admin** tab appears in the navigation — it is only shown to the administrator.');
    await admin.page.goto(`${BASE}/admin`, { waitUntil: 'load' });
    await shot(admin.page, 'The Admin page. It shows which model is driving turns, the security posture, the applied database migrations, the command-policy floor, and a durable audit log of everything the agent has done.', { full: true });
  },
);

await chapterRun(
  'Add two people',
  'A person in qm is a directory entry: an id, a display name, and an email address. There is ' +
    'no invitation to accept and no password to choose — adding someone means they may now sign ' +
    'in with a link to that address, whenever they like. Each person gets a personal scope that ' +
    'nobody else can read: their own memory, files, credentials and working directory.',
  async () => {
    step('From the Admin page, click **People & accounts →**.');
    await admin.page.goto(`${BASE}/admin/people`, { waitUntil: 'load' });
    await shot(admin.page, 'The People page. The badge at the top shows which membership mode you are running.', { full: true });

    note(
      'Two membership modes are available, chosen with `[auth].membership_mode` in ' +
        '`config.toml`. **allowlist** (the default) admits only people listed here or matched ' +
        'by a rule in the config — nobody else can sign in. **denylist** admits anyone with a ' +
        'valid address unless you deactivate them, which suits a deployment where something ' +
        'else already bounds who can reach the server, such as a VPN or an SSO proxy. Bound it ' +
        'with `allowed_domains` so only your company\'s addresses are accepted.',
    );

    step('Fill in **Email address** and **Display name**, optionally set a **Principal id** (otherwise it is derived from the address), and click **Add**. Repeat for the second person.');
    for (const [email, name, id] of [
      ['ada@acme.test', 'Ada Lovelace', 'ada'],
      ['dana@acme.test', 'Dana Scott', 'dana'],
    ]) {
      await admin.page.fill('#email', email);
      await admin.page.fill('#display_name', name);
      await admin.page.fill('#principal_id', id);
      await Promise.all([
        admin.page.waitForNavigation({ timeout: 30_000 }),
        admin.page.click('form[action="/admin/people/invite"] button[type=submit]', { noWaitAfter: true }),
      ]);
    }
    const listed = await admin.page.locator('table').first().textContent();
    check(/ada/.test(listed) && /dana/.test(listed), 'both people should be listed');
    await shot(admin.page, 'Ada and Dana are now in the directory and can sign in whenever they like. Tell them the URL; they do the rest themselves.', { full: true });

    note(
      'To offboard someone, click **Deactivate**. That refuses their next sign-in and ' +
        'immediately invalidates every browser session and API key they hold — you do not have ' +
        'to hunt them down. **Restore** puts them back. Deactivating is the offboarding verb in ' +
        'both membership modes.',
    );
    note(
      'If you run the Telegram or Slack connector, the **Link a chat account** form at the ' +
        'bottom of this page binds a person\'s chat account to their directory entry, so their ' +
        'messages run as them with their scopes rather than as an anonymous guest. You need ' +
        'their platform user id — a Telegram numeric id, or a Slack `U…` id.',
    );
  },
);

await chapterRun(
  'Put them both in a group',
  'A group is a set of people who share one scope: one memory, one working directory, one set ' +
    'of files. What the agent learns while working in the group belongs to the group, not to ' +
    'whoever happened to type the message. This is the difference between qm and a personal ' +
    'assistant — the same agent works for individuals and for teams, and keeps the boundary.',
  async () => {
    step('From the Admin page, click **Groups & conversations →**.');
    await admin.page.goto(`${BASE}/admin/groups`, { waitUntil: 'load' });

    step('Enter a **Name** for the group, tick the **Members** who belong to it, and click **Save group**. A group needs at least two people.');
    await admin.page.fill('#name', 'Ops');
    await admin.page.fill('#id', 'ops');
    for (const id of ['ada', 'dana', 'admin']) {
      await admin.page.check(`input[name=members][value="${id}"]`);
    }
    await shot(admin.page, 'Creating the Ops group with Ada, Dana and the administrator in it.', { full: true });

    await Promise.all([
      admin.page.waitForNavigation({ timeout: 30_000 }),
      admin.page.click('form[action="/admin/groups/save"] button[type=submit]', { noWaitAfter: true }),
    ]);
    const groups = await admin.page.locator('main').textContent();
    check(/group:ops/.test(groups), 'the group scope should exist');
    await shot(admin.page, 'The group now exists as the scope `group:ops`. Its three members can open sessions in it; nobody else can see it at all.', { full: true });

    note(
      'Groups are keyed by their participants, so saving the same set of people again updates ' +
        'that group rather than creating a second one with the same members. That is what lets ' +
        'a multi-person conversation arriving from any surface resolve to the same group every ' +
        'time.',
    );
    note(
      'If you run a chat connector, use **Link a conversation to a group** at the bottom of ' +
        'this page to point a real Telegram group or Slack channel at `group:ops`. The chat and ' +
        'the web UI then share one memory and one workspace — a decision made in Slack is ' +
        'visible on the web, and vice versa. Without a binding, a connector derives its own ' +
        'separate scope from the chat id.',
    );
  },
);

await chapterRun(
  'Ada works with the agent privately',
  'Now someone actually uses it. Ada signs in with her own link and asks the agent to build ' +
    'something in her personal scope. Behind that scope is a durable working directory — a ' +
    'computer that persists between conversations, where anything the agent installs stays ' +
    'installed.',
  async () => {
    step('Ada opens the same URL, enters **her own** email address, and follows her sign-in link. She never needed an invitation code.');
    await signIn(ada, 'ada@acme.test');
    await ada.page.goto(`${BASE}/`, { waitUntil: 'load' });
    await shot(ada.page, "Ada's dashboard. She can reach her own scope and the Ops group. She cannot see Dana's private scope, and there is no Admin tab for her.", { full: true });

    step('Click **Sessions**, choose the scope to work in — here `personal:ada` — give the session a title, and click **Start**.');
    await openSession(ada, 'personal:ada', 'Disk space script');

    step('Type what you want in the composer and press Enter. Ask for real work, not just a question.');
    await ask(
      ada,
      'Write a shell script at workspace/diskcheck.sh that prints the three largest files under ' +
        'a directory given as $1, defaulting to the current directory. Use the write tool, then ' +
        'run it with execute against . to prove it works, and tell me what it printed.',
    );
    const reply = await lastReply(ada.page);
    check(reply.length > 0, 'the agent should have replied');
    await shot(ada.page, 'The agent wrote the script and ran it. The tool calls and their real output appear on the transcript as their own entries — you can see exactly what it did, not just what it says it did.', { full: true });

    note(
      'That file is genuinely on disk in Ada\'s scope. A later conversation can pick it up, ' +
        'because the workspace is durable. Anything the agent learns about how Ada likes to ' +
        'work goes into her memory notebook, which you can read and edit under **Memory**.',
    );
    note(
      'Some commands stop and ask first. A recursive delete, a force push or destructive SQL ' +
        'raises an approval card with the exact command and the rule it matched, and you choose ' +
        '**Just this once**, **Every time in this session**, or **Always, for me**. Genuinely ' +
        'destructive commands such as `mkfs` are refused outright and cannot be approved. This ' +
        'floor applies in every security posture.',
    );
  },
);

await chapterRun(
  'The whole group works together',
  'Finally, the multiplayer part. Ada brings her work into the group, and Dana — a different ' +
    'person, in a different browser, with her own session — picks it up and asks for a change. ' +
    'Both are talking to the same agent in the same scope, and the group remembers.',
  async () => {
    step('Ada clicks **Sessions**, chooses `group:ops` this time, and starts a session there.');
    await openSession(ada, 'group:ops', 'Disk check rollout');

    step('She asks the agent to put the work somewhere the team can reach it, and to record who owns it.');
    await ask(
      ada,
      'Use the write tool to put a copy of a disk-check script at workspace/diskcheck.sh in this ' +
        'group workspace, then use the memory tool to record that Ops owns the disk-check script. ' +
        'Confirm briefly.',
    );
    await shot(ada.page, 'Ada working in the Ops group. The scope is shown under the title, so it is always clear whether you are somewhere private or somewhere shared.', { full: true });

    const groupUrl = ada.page.url();

    step('Dana signs in with her own address, opens **Sessions**, and finds the same session waiting for her — she was never sent a link to it. She can see it because she is in the group.');
    await signIn(dana, 'dana@acme.test');
    await dana.page.goto(`${BASE}/sessions`, { waitUntil: 'load' });
    await shot(dana.page, "Dana's session list. The group session Ada started is there, alongside her own.", { full: true });

    await dana.page.goto(groupUrl, { waitUntil: 'load' });

    step('Dana opens it and asks for a change, in the same conversation.');
    await ask(
      dana,
      'Change the script so it also prints the total size of the directory at the end, then run ' +
        'it against . and show me the output.',
    );
    const danaReply = await lastReply(dana.page);
    check(danaReply.length > 0, 'the agent should answer Dana too');
    await shot(dana.page, 'The agent made the change — in the group workspace, to the file Ada put there. One conversation, two people, one agent that has the full context of both.', { full: true });

    step('Open **Memory** and choose the group to see what the agent has learned on the team\'s behalf.');
    await admin.page.goto(`${BASE}/memory/group:ops`, { waitUntil: 'load' });
    await shot(admin.page, "The group's memory notebook. What the agent learned here belongs to the Ops group — it is not in Ada's private notebook, and not in Dana's.", { full: true });

    note(
      'This is the whole point of scopes. Ada and Dana each have a private workspace the other ' +
        'cannot read, and a shared one where the agent keeps a single memory for the team. The ' +
        'same boundary holds however the message arrives — the web UI, Slack, Telegram, or a ' +
        'scheduled job — because every turn goes through one orchestrator that resolves the ' +
        'scope before the model sees anything.',
    );
  },
);

await browser.close();

// ---------------------------------------------------------------------------
// Generate the guide
// ---------------------------------------------------------------------------

const stamp = new Date().toISOString().replace(/\.\d+Z$/, 'Z');
const esc = (s) =>
  String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

/// The small slice of Markdown the prose above uses, rendered for HTML:
/// `**bold**`, `` `code` `` and `[text](url)`. Escaping happens first, so a
/// link's text and href are already safe by the time they are wrapped.
const inline = (s) =>
  esc(s)
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
    .replace(/`([^`]+)`/g, '<code>$1</code>')
    .replace(/\[([^\]]+)\]\((https?:[^)\s]+)\)/g, '<a href="$2">$1</a>');

const BACKGROUND = {
  what: [
    'qm-rs is a **multiplayer agent harness for work**. Most AI agents are built as personal ' +
      'assistants: one person, one context, one history. That model breaks down the moment a ' +
      'team tries to share one — either everybody sees everybody\'s notes, or each person gets ' +
      'an assistant that knows nothing about the company.',
    'qm-rs takes a different position. Every person and every room gets its own **scope**: its own ' +
      'memory, files, credentials, permissions, scheduled jobs, and a durable working directory ' +
      'the agent can actually run commands in. People work independently without stepping on ' +
      'each other, and the same agent also works with everyone together in shared groups and ' +
      'channels.',
    '`qm-rs` is an independent Rust implementation of that idea on local SQLite. It is one ' +
      'binary and one database file, with a server-rendered web UI, connectors for Slack and ' +
      'Telegram, and an HTTP API — no build step and nothing to orchestrate. It **learns ' +
      'heavily from** [QM](https://github.com/yc-software/qm), the TypeScript project that ' +
      'established this design, borrowing its concepts and several of its specific mechanisms ' +
      'without being a port of it.',
  ],
  why: [
    'The design turns on one idea: **every turn goes through a single orchestrator**. Whether a ' +
      'message arrives from the web UI, from Slack, from Telegram, or from a scheduled job, it ' +
      'takes the same path — resolve the scope, screen the input, assemble the prompt, drive the ' +
      'model over a small fixed set of tools, and write the result down. Surfaces never reach ' +
      'past the orchestrator, which is what keeps one identity and one policy across all of them.',
    'That is also what makes the security properties hold everywhere at once. A command policy ' +
      'that pauses a recursive delete pauses it in Slack too. A scope boundary that stops the ' +
      'agent quoting your private notes in a group holds no matter which surface asked.',
  ],
  before: [
    'You need a running qm-rs server. See the [README](https://github.com/second-state/qm-rs) ' +
      'for install instructions. In short: `cargo run` starts it on port 8080 with a mock ' +
      'harness that needs no credentials, and pointing `[harness]` at any OpenAI-compatible ' +
      'endpoint with tool calling makes it real.',
    'Set `[auth].admin_email` in `config.toml` to your own address before you start, or nobody ' +
      'will be able to sign in.',
  ],
};

// ---- Markdown, so it renders on GitHub ------------------------------------

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const stripMd = (s) => s;

const md = [
  '# Getting started with qm-rs',
  '',
  '*Set up a team from nothing: sign in, add people, group them, and put the agent to work —',
  'privately and together.*',
  '',
  '---',
  '',
  '## What qm is',
  '',
  ...BACKGROUND.what.flatMap((p) => [p, '']),
  '## Why it is built this way',
  '',
  ...BACKGROUND.why.flatMap((p) => [p, '']),
  '## Before you start',
  '',
  ...BACKGROUND.before.flatMap((p) => [p, '']),
  '---',
  '',
  '## Contents',
  '',
  ...chapters.map((c, i) => `${i + 1}. [${c.title}](#${slug(c.title)})`),
  '',
]
  .concat(
    chapters.flatMap((c) => {
      let n = 0;
      return [
        '---',
        '',
        `## ${c.title}`,
        '',
        c.status === 'fail' ? `> ⚠️ **This step failed when the guide was generated:** ${c.error}\n` : '',
        c.intro,
        '',
        ...c.steps.flatMap((s) => {
          if (s.kind === 'step') {
            n += 1;
            return [`**${n}.** ${stripMd(s.text)}`, ''];
          }
          if (s.kind === 'note') return [`> ${stripMd(s.text)}`, ''];
          return [`![${s.caption.replace(/[[\]]/g, '')}](${s.file})`, '', `*${s.caption}*`, ''];
        }),
      ];
    }),
  )
  .concat([
    '---',
    '',
    '## Where to go next',
    '',
    '- **Skills** — write a reusable instruction bundle the agent follows. Skills are scoped and',
    '  signed, so a tampered skill is hidden from every turn rather than executed.',
    '- **Crons** — ask the agent to schedule work, or add it yourself. Each scheduled instant',
    '  fires exactly once, and the schedule advances whatever the outcome.',
    '- **Keychain** — store credentials per scope. They are materialized as environment variables',
    '  when the agent runs a command, and never rendered, logged, or written to the audit trail.',
    '- **Connectors** — put the same agent in Slack and Telegram, sharing the scopes you just set up.',
    '',
    '---',
    '',
    `*Generated on ${stamp} from a real run against \`${MODEL}\`. Every screenshot is the actual`,
    'application and every agent reply is a real model turn — regenerate with',
    '`bash scripts/tutorial.sh`.*',
    '',
  ])
  .join('\n');

writeFileSync(`${OUT}/README.md`, md);

// ---- HTML, for GitHub Pages ----------------------------------------------

const html = `<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Getting started with qm-rs</title>
<meta name="description" content="Set up a team on qm-rs: sign in, add people, create a group, and put the agent to work privately and together.">
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E%3Ctext y='.9em' font-size='90'%3E%F0%9F%A6%AB%3C/text%3E%3C/svg%3E">
<style>
  :root { --ink:#16181d; --paper:#fbfbfd; --panel:#fff; --line:#e3e5ec; --accent:#3557d6;
          --accent-soft:#edf1fe; --muted:#5c6070; --bad:#b4232b; }
  @media (prefers-color-scheme: dark) {
    :root { --ink:#e8eaf0; --paper:#14161b; --panel:#1c1f26; --line:#2b3039; --accent:#7d9bff;
            --accent-soft:#232a3d; --muted:#9aa0b0; --bad:#f28b8b; }
  }
  * { box-sizing:border-box; }
  body { font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
         background:var(--paper); color:var(--ink); margin:0; line-height:1.65; font-size:16px; }
  a { color:var(--accent); }
  header { background:var(--ink); color:var(--paper); padding:44px 30px 38px; }
  @media (prefers-color-scheme: dark) { header { background:#0d0f13; color:var(--ink); } }
  header .wrap { max-width:820px; margin:0 auto; }
  header h1 { margin:0 0 10px; font-size:2rem; letter-spacing:-.025em; }
  header p { margin:0; opacity:.85; font-size:1.02rem; max-width:60ch; }
  header code { background:rgba(255,255,255,.14); padding:1px 6px; border-radius:5px; font-size:.9em; }
  .wrap { max-width:820px; margin:0 auto; padding:0 30px; }
  .intro-block { padding:34px 0 6px; }
  .intro-block h2 { font-size:1.3rem; letter-spacing:-.01em; margin:28px 0 10px; }
  .intro-block p { color:var(--ink); }
  nav.toc { background:var(--panel); border:1px solid var(--line); border-radius:12px;
            padding:18px 24px; margin:30px 0 10px; }
  nav.toc h2 { font-size:.78rem; text-transform:uppercase; letter-spacing:.08em;
               color:var(--muted); margin:0 0 8px; }
  nav.toc ol { margin:0; padding-left:22px; }
  nav.toc li { margin:4px 0; }
  section { padding:38px 0; border-top:1px solid var(--line); }
  section h2 { font-size:1.5rem; letter-spacing:-.02em; margin:0 0 10px; }
  .intro { color:var(--muted); font-size:1.02rem; margin:0 0 8px; }
  ol.steps { list-style:none; counter-reset:s; padding:0; margin:26px 0; }
  ol.steps li { counter-increment:s; position:relative; padding:0 0 0 44px; margin:0 0 18px; }
  ol.steps li::before {
    content:counter(s); position:absolute; left:0; top:1px;
    width:28px; height:28px; border-radius:50%;
    background:var(--accent); color:#fff; font-size:.85rem; font-weight:700;
    display:flex; align-items:center; justify-content:center;
  }
  figure { margin:26px 0; }
  figure img { width:100%; border:1px solid var(--line); border-radius:12px; display:block; }
  figcaption { font-size:.9rem; color:var(--muted); margin-top:10px; }
  .note { background:var(--accent-soft); border-left:3px solid var(--accent);
          padding:14px 18px; border-radius:0 10px 10px 0; margin:20px 0; font-size:.96rem; }
  .fail { color:var(--bad); font-weight:600; }
  code { background:var(--panel); border:1px solid var(--line); padding:1px 5px;
         border-radius:5px; font-size:.88em;
         font-family:ui-monospace,SFMono-Regular,Menlo,monospace; }
  footer { border-top:1px solid var(--line); padding:30px 0 60px; color:var(--muted); font-size:.9rem; }
  ul.next { padding-left:20px; }
  ul.next li { margin:8px 0; }
</style></head><body>
<header><div class="wrap">
  <h1>Getting started with qm-rs</h1>
  <p>Set up a team from nothing: sign in, add people, group them, and put the agent to work —
     privately and together.</p>
</div></header>

<div class="wrap intro-block">
  <h2>What qm is</h2>
  ${BACKGROUND.what.map((p) => `<p>${inline(p)}</p>`).join('\n  ')}
  <h2>Why it is built this way</h2>
  ${BACKGROUND.why.map((p) => `<p>${inline(p)}</p>`).join('\n  ')}
  <h2>Before you start</h2>
  ${BACKGROUND.before.map((p) => `<p>${inline(p)}</p>`).join('\n  ')}

  <nav class="toc">
    <h2>What this guide covers</h2>
    <ol>${chapters.map((c, i) => `<li><a href="#c${i}">${esc(c.title)}</a></li>`).join('')}</ol>
  </nav>
</div>

<div class="wrap">
${chapters
  .map((c, i) => {
    // Instructions render as one numbered list; screenshots and notes sit
    // between them in document order.
    const body = [];
    let open = false;
    for (const s of c.steps) {
      if (s.kind === 'step') {
        if (!open) {
          body.push('<ol class="steps">');
          open = true;
        }
        body.push(`<li>${inline(s.text)}</li>`);
      } else {
        if (open) {
          body.push('</ol>');
          open = false;
        }
        body.push(
          s.kind === 'shot'
            ? `<figure><a href="${s.file}" target="_blank"><img src="${s.file}" loading="lazy" alt="${esc(s.caption)}"></a><figcaption>${inline(s.caption)}</figcaption></figure>`
            : `<div class="note">${inline(s.text)}</div>`,
        );
      }
    }
    if (open) body.push('</ol>');
    return `<section id="c${i}">
  <h2>${i + 1}. ${esc(c.title)}</h2>
  ${c.status === 'fail' ? `<p class="fail">⚠️ This step failed when the guide was generated: ${esc(c.error)}</p>` : ''}
  <p class="intro">${inline(c.intro)}</p>
  ${body.join('\n  ')}
</section>`;
  })
  .join('\n')}

<section>
  <h2>Where to go next</h2>
  <ul class="next">
    <li><strong>Skills</strong> — write a reusable instruction bundle the agent follows. Skills are
        scoped and signed, so a tampered skill is hidden from every turn rather than executed.</li>
    <li><strong>Crons</strong> — ask the agent to schedule work, or add it yourself. Each scheduled
        instant fires exactly once, and the schedule advances whatever the outcome.</li>
    <li><strong>Keychain</strong> — store credentials per scope. They are materialized as
        environment variables when the agent runs a command, and never rendered, logged, or
        written to the audit trail.</li>
    <li><strong>Connectors</strong> — put the same agent in Slack and Telegram, sharing the scopes
        you just set up.</li>
  </ul>
</section>

<footer>
  Generated on ${esc(stamp)} from a real run against <code>${esc(MODEL)}</code>.
  Every screenshot is the actual application and every agent reply is a real model turn —
  regenerate with <code>bash scripts/tutorial.sh</code>.
</footer>
</div>
</body></html>`;

writeFileSync(`${OUT}/index.html`, html);
// The gateway endpoint is an internal deployment detail and this file is
// committed to a public repository, so only the model id is recorded.
writeFileSync(`${OUT}/tutorial.json`, JSON.stringify({ stamp, model: MODEL, chapters }, null, 2));

log('');
log(`${chapters.length - failures}/${chapters.length} chapters · ${seq} screenshots`);
log(`guide: ${OUT}/README.md`);
process.exit(failures === 0 ? 0 : 1);
